### ISSUE TITLE
Need to create a new/expand the current "health" config object

### ISSUE THREAD

**Issue by jrcast** [ForgeRock/forgeops-cli#58]
The "health" object defines the rules we check in the doctor/status commands. We should expand these object to make it a project-wide config. This "commandConfig" can define all the defaults for the whole project. 

The current "health" object would be part of this config. Example: 

```yaml
kind: health
version: v1alpha
metadata:
  name: forgeops-operators
spec:
  platform:
    importantSecrets: [...]
    components: ["base", "ds", "apps", "ui"]
    tieredDeploy: true
    printSecrets: true
    printURLs: true
    etc: etc
  health:
    resources:
      - resource: deployments
        name: secret-agent-controller-manager
        apiversion: v1
        group: apps
        checks:
          - expression: status.availableReplicas == 1
            timeout: 0s

```
